spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab1
    username: hits
    password: hits
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8090
