spring:
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://localhost:5432/lab1
    user: hits
    password: hits
#    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/lab1
    username: hits
    password: hits
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8090
